name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: astro build cache
        id: astro-build-cache
        uses: actions/cache@v3
        with:
          path: .cache
          key: ${{ runner.os }}-astro-build-${{ hashFiles('**/cache.json') }}

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm

      - name: install dependencies
        run: npm ci

      - name: check
        run: npm run astro check

      - name: calculate hash
        id: hash
        run: echo "cachehash=${{ hashFiles('**/cache.json') }}" >> $GITHUB_OUTPUT

      - name: build
        run: npm run build

      - name: check cache
        id: check-cache
        run: |
          if [ ${{ steps.hash.outputs.cachehash }} == ${{ hashFiles('**/cache.json') }} ]
          then
            echo "cachepass=true" >> $GITHUB_OUTPUT
          else
            echo "cachepass=false" >> $GITHUB_OUTPUT
          fi

      - name: cache comment
        if: ${{ steps.check-cache.outputs.cachepass == 'true' }}
        uses: GrantBirki/comment@v2.0.5
        with:
          file: .github/cache-msg.md
