name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: astro build cache
        id: astro-build-cache
        uses: actions/cache@v3
        with:
          path: .cache
          key: ${{ runner.os }}-astro-build-${{ hashFiles('**/cache.json') }}

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm

      - name: install dependencies
        run: npm ci

      - name: check
        run: npm run astro check

      # get the hash of our 'cache' file before the build
      - name: calculate hash
        id: hash
        run: echo "cachehash=${{ hashFiles('**/cache.json') }}" >> $GITHUB_OUTPUT

      - name: build
        run: npm run build

      # compare the hashes after the build completes
      - name: check cache
        id: check-cache
        run: |
          if [[ "${{ steps.hash.outputs.cachehash }}" == "${{ hashFiles('**/cache.json') }}" ]]
          then
            echo "hashes are equal - OK"
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "hashes are not equal - FAIL"
            echo "expected: ${{ steps.hash.outputs.cachehash }}"
            echo "actual: ${{ hashFiles('**/cache.json') }}"
            echo "success=false" >> $GITHUB_OUTPUT
          fi

      # if the hashes don't match, we need to update the cache, so we leave a comment on the PR
      - name: cache comment
        if: ${{ steps.check-cache.outputs.success == 'false' }} && github.event_name == 'pull_request'
        uses: GrantBirki/comment@v2.0.5
        with:
          file: .github/cache-msg.md

      # if the hashes don't match, we now fail the CI job
      - name: cache failure
        if: ${{ steps.check-cache.outputs.success == 'false' }}
        run: echo "hash mismatch! Please run 'npm run all' and commit the changes." && exit 1
